# https://jekyllrb.com/docs/step-by-step/09-collections/#configuration

# Site settings
title:          개발자 한선우
baseurl:        ""
url:            "https://yadon079.github.io"

# Google Analytics
google_analytics:

# Author
author:
  name:         Sunwoo Han
  url:          https://yadon079.github.io
  email:        thankowl777@kakao.com
  github:       yadon079

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Conversion
markdown:       kramdown
highlighter:    rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks ( http://jekyllrb-ko.github.io/docs/permalinks/ )
permalink:     /:year/:categories/:title
paginate:      5
paginate_path: /page/:num

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
img_url: /assets/img
category_list: [ algorithm, coding test, java, java study halle, spring, project, cs, data structure, til, review, etc ]
